version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d auth']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile.local
    restart: on-failure
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      NODE_ENV: development
      PORT: 9000
    volumes:
      - ./app/api:/opt/app
