name: Deploy API to AWS Lambda

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: aws-lambda-nodejs-image
  IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f app/api/Dockerfile app/api

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="environment=prod" \
            -var="ecr_repo_url=${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}" \
            -var="image_tag=${IMAGE_TAG}" \
            -var="aws_account_id=${{ env.AWS_ACCOUNT_ID }}" \
            -var="aws_role_name=my-node-app-prod-lambda-exec"
        working-directory: ./terraform
